#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# ── Up front: dependencies and the plugin config path ──────────────────────
missing=()
for dep in curl jq; do
  command -v "$dep" >/dev/null 2>&1 || missing+=("$dep")
done
if (( ${#missing[@]} > 0 )); then
  _clear
  printf '\n%s%s  Missing dependencies: %s%s\n\n' "$BOLD" "$RED" "${missing[*]}" "$RESET"
  say "This wizard uses curl and jq to talk to the Telegram API."
  say "Install them and run it again:"
  note "Debian/Ubuntu:    sudo apt install curl jq"
  note "macOS (Homebrew): brew install curl jq"
  printf '\n'
  exit 1
fi

# ENV_FILE must point at the plugin config dir before any ask_secret/write_env,
# so a re-run offers the values already saved there.
HERDR_CMD="${HERDR_BIN_PATH:-herdr}"
config_dir=""
config_dir_assumed=0
if command -v "$HERDR_CMD" >/dev/null 2>&1; then
  config_dir=$("$HERDR_CMD" plugin config-dir alherdr.agent-alerts 2>/dev/null) || config_dir=""
fi
if [[ -z "$config_dir" ]]; then
  config_dir_assumed=1
  config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/herdr/plugins/config/alherdr.agent-alerts"
fi
if (( config_dir_assumed )); then
  printf '\n'
  warn "Could not resolve the config directory with '${HERDR_CMD} plugin config-dir alherdr.agent-alerts'."
  warn "Assuming the default path: $config_dir"
  warn "If the plugin uses another path, the configuration will not reach it."
  pause "Press Enter to continue anyway."
fi
if ! mkdir -p "$config_dir"; then
  warn "Could not create the config directory: $config_dir"
  exit 1
fi
ENV_FILE="$config_dir/.env"

banner "Agent Alerts · Telegram"

# ── Stage 1: create the bot with BotFather ─────────────────────────────────
stage "Create the bot with BotFather"
say "You do not have a Telegram bot yet. We create one with BotFather, the official"
say "Telegram bot for creating and managing bots."
say ""
open_url "https://t.me/BotFather"
say ""
step "Press Start if this is the first time you talk to BotFather."
step "Send /newbot."
step "When it asks for a name, type the display name you want (for example: Agent alerts)."
step "When it asks for a username, pick one that is free and ends in bot (for example: my_alerts_bot)."
step "BotFather replies with the access token, next to 'Use this token to access the HTTP API'."
step "Copy the full token: the numbers, the colon and the rest."
note "The token is like a password: do not share it or paste it anywhere else."
note "If you lose it: @BotFather → /mybots → your bot → API Token."
say ""
ask_secret TELEGRAM_BOT_TOKEN "Paste the token (it will not be shown):"
while [[ -z "${TELEGRAM_BOT_TOKEN:-}" ]]; do
  warn "You pasted nothing."
  ask_secret TELEGRAM_BOT_TOKEN "Paste the token (it will not be shown):"
done

# ── Stage 2: validate the token with getMe ─────────────────────────────────
stage "Validate the token with Telegram"
say "We check the token against the Telegram API (getMe) before going on."
say "If it is wrong, I tell you and you can paste it again."
say ""

BOT_USERNAME=""
while true; do
  say "Querying Telegram..."
  getme_response=""
  curl_rc=0
  getme_response=$(curl -sS --max-time 20 "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" 2>&1) || curl_rc=$?

  if (( curl_rc != 0 )); then
    warn "Could not connect to api.telegram.org (curl, code $curl_rc)."
    note "$getme_response"
  elif jq -e '.ok == true' >/dev/null 2>&1 <<<"$getme_response"; then
    BOT_USERNAME=$(jq -r '.result.username // empty' <<<"$getme_response")
    if [[ -n "$BOT_USERNAME" ]]; then
      printf '  %s✓%s Token valid. Bot: @%s\n' "$GREEN" "$RESET" "$BOT_USERNAME"
      break
    fi
    warn "Telegram accepted the token but did not return the bot name."
  else
    telegram_description=$(jq -r '.description // empty' <<<"$getme_response" 2>/dev/null || true)
    if [[ -n "$telegram_description" ]]; then
      warn "Telegram replied: $telegram_description"
    else
      warn "Unexpected reply from Telegram:"
      note "$getme_response"
    fi
  fi

  say ""
  say "Check that you copied the whole token: number, colon and the final string."
  note "You can see it again in @BotFather → /mybots → your bot → API Token."
  ask_secret TELEGRAM_BOT_TOKEN "Paste the token again (it will not be shown):"
done

# ── Stage 3: discover the chat id with getUpdates ──────────────────────────
stage "Discover your chat id"
say "Telegram does not let a bot message you first: you have to start the chat yourself."
say ""
open_url "https://t.me/$BOT_USERNAME"
say ""
step "In the chat with @${BOT_USERNAME}, press Start and send any message (for example: hello)."
step "Come back to this terminal."

TELEGRAM_CHAT_ID=""
while true; do
  pause "Press Enter once you have sent the message."
  say "Looking for your message on Telegram (getUpdates)..."
  updates_response=""
  curl_rc=0
  updates_response=$(curl -sS --max-time 20 "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates" 2>&1) || curl_rc=$?

  if (( curl_rc != 0 )); then
    warn "Could not connect to api.telegram.org (curl, code $curl_rc)."
    note "$updates_response"
  elif jq -e '.ok == true' >/dev/null 2>&1 <<<"$updates_response"; then
    TELEGRAM_CHAT_ID=$(jq -r '[.result[] | (.message // .edited_message // .channel_post // empty) | .chat.id // empty] | last // empty' <<<"$updates_response")
    if [[ -n "$TELEGRAM_CHAT_ID" ]]; then
      printf '  %s✓%s Chat detected: %s\n' "$GREEN" "$RESET" "$TELEGRAM_CHAT_ID"
      break
    fi
    warn "getUpdates does not return any message from you yet."
  else
    telegram_description=$(jq -r '.description // empty' <<<"$updates_response" 2>/dev/null || true)
    if [[ -n "$telegram_description" ]]; then
      warn "Telegram replied: $telegram_description"
    else
      warn "Unexpected reply from Telegram:"
      note "$updates_response"
    fi
  fi

  say ""
  say "Two common causes:"
  step "You have not messaged the bot yet: open @${BOT_USERNAME}, press Start, send it a message and come back."
  step "The bot has a webhook configured: while it exists, getUpdates returns no messages. Delete it with Telegram's deleteWebhook API call, or create another bot."
  say ""
  if ! confirm "Try detection again?"; then
    warn "Without a chat id I cannot complete the setup."
    say "Send a message to @${BOT_USERNAME} and run again: bash scripts/wizard.sh"
    exit 1
  fi
done

# ── Stage 4: persist both values ───────────────────────────────────────────
stage "Save the configuration"
say "I write the token and the chat id to the plugin .env:"
note "$ENV_FILE"
if (( config_dir_assumed )); then
  warn "Could not resolve the path with Herdr; continuing with the default path I warned you about."
fi
say ""
warn "This file holds your Telegram token: do not commit it to git or share it."
say ""
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"
if chmod 600 "$ENV_FILE"; then
  printf '  %s✓%s Permissions for your user only (chmod 600).\n' "$GREEN" "$RESET"
else
  warn "Could not apply chmod 600; check the permissions on $ENV_FILE by hand."
fi
note "The plugin re-reads this file on every event: no Herdr restart needed."

# ── Stage 5: live test message ─────────────────────────────────────────────
stage "Send a test message"
say "I send you a real Telegram message. It proves everything works."
say ""

TEST_TEXT="Agent Alerts test message. If you can read this, the Telegram configuration works."
test_sent=0
while (( test_sent == 0 )); do
  telegram_payload=$(jq -n --arg chat "$TELEGRAM_CHAT_ID" --arg text "$TEST_TEXT" '{chat_id: ($chat | tonumber? // $chat), text: $text}')
  send_response=""
  curl_rc=0
  send_response=$(curl -sS --max-time 20 -X POST \
    "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
    -H 'Content-Type: application/json' \
    --data "$telegram_payload" 2>&1) || curl_rc=$?

  if (( curl_rc != 0 )); then
    warn "Could not connect to api.telegram.org (curl, code $curl_rc)."
    note "$send_response"
  elif jq -e '.ok == true' >/dev/null 2>&1 <<<"$send_response"; then
    test_sent=1
    printf '  %s✓%s Message sent.\n' "$GREEN" "$RESET"
  else
    telegram_description=$(jq -r '.description // empty' <<<"$send_response" 2>/dev/null || true)
    if [[ -n "$telegram_description" ]]; then
      warn "Telegram replied: $telegram_description"
    else
      warn "Unexpected reply from Telegram:"
      note "$send_response"
    fi
  fi

  if (( test_sent == 0 )); then
    if ! confirm "Send the test message again?"; then
      SKIPPED+=("Telegram test: send a message by hand and re-run scripts/wizard.sh")
      break
    fi
  fi
done

if (( test_sent == 1 )); then
  say ""
  say "Check your phone: the message should be in the chat with @${BOT_USERNAME}."
  pause "Press Enter once you have seen it."
fi

finish

# ── Closing: day-to-day use ────────────────────────────────────────────────
printf '  %sDay-to-day use%s\n' "$BOLD" "$RESET"
step "Enable or disable alerts:    herdr plugin action invoke alherdr.agent-alerts.toggle"
step "Send another test message:   herdr plugin action invoke alherdr.agent-alerts.send-test"
step "View the plugin logs:        herdr plugin log list --plugin alherdr.agent-alerts"
printf '\n'
note "To change the token or the chat id, run again: bash scripts/wizard.sh"
